In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler
import joblib

In [59]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/CKD Project/kidney_disease.csv")
df.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wbcc,rbcc,htn,dm,cad,appet,pe,ane,class
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,44.0,7800.0,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,38.0,6000.0,NaN,no,no,no,good,no,no,ckd
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31.0,7500.0,NaN,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32.0,6700.0,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35.0,7300.0,4.6,no,no,no,good,no,no,ckd

**Impute Missing Values Using MICE**

In [60]:
CAT_COLS = ['rbc','pc','pcc','ba','htn','dm','cad','appet','pe','ane']

df_encoded = df.copy()
binary_map = {'yes':1,'no':0,'normal':1,'abnormal':0, 'present':1,'notpresent':0,'good':1,'poor':0}
for col in CAT_COLS:
    df_encoded[col] = df_encoded[col].map(binary_map)
df_encoded['class'] = df_encoded['class'].map({'ckd':1, 'notckd':0})
df_encoded.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wbcc,rbcc,htn,dm,cad,appet,pe,ane,class
0,48.0,80.0,1.020,1.0,0.0,NaN,1.0,0.0,0.0,121.0,...,44.0,7800.0,5.2,1.0,1.0,0.0,1.0,0.0,0.0,1
1,7.0,50.0,1.020,4.0,0.0,NaN,1.0,0.0,0.0,NaN,...,38.0,6000.0,NaN,0.0,0.0,0.0,1.0,0.0,0.0,1
2,62.0,80.0,1.010,2.0,3.0,1.0,1.0,0.0,0.0,423.0,...,31.0,7500.0,NaN,0.0,1.0,0.0,0.0,0.0,1.0,1
3,48.0,70.0,1.005,4.0,0.0,1.0,0.0,1.0,0.0,117.0,...,32.0,6700.0,3.9,1.0,0.0,0.0,0.0,1.0,1.0,1
4,51.0,80.0,1.010,2.0,0.0,1.0,1.0,0.0,0.0,106.0,...,35.0,7300.0,4.6,0.0,0.0,0.0,1.0,0.0,0.0,1

In [61]:
target_col  = df_encoded['class']
df_encoded.drop(columns=['class'], inplace=True)

In [62]:
scaler = StandardScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df_encoded), columns=df_encoded.columns.tolist())

In [63]:
knn_imputer = KNNImputer(n_neighbors=5, weights='distance')
df_imputed = pd.DataFrame(knn_imputer.fit_transform(df_scaled), columns=df_encoded.columns.tolist())

In [64]:
# ── 7. Inverse scale to get real values back ──
df_imputed = pd.DataFrame(scaler.inverse_transform(df_imputed), columns=df_encoded.columns.tolist())

In [65]:
# Correct dtypes
INT_COLS   = ['age','bp','al','su','bgr','pcv','wbcc','sod']
FLOAT_COLS = ['sg','bu','sc','pot','hemo','rbcc']

# Clip categoricals to 0/1
for col in CAT_COLS:
    df_imputed[col] = df_imputed[col].clip(0, 1).round().astype(int)
for col in INT_COLS:
    df_imputed[col] = df_imputed[col].round().astype(int)
for col in FLOAT_COLS:
    df_imputed[col] = df_imputed[col].round(3)

In [66]:
df_imputed.sample(50)

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,hemo,pcv,wbcc,rbcc,htn,dm,cad,appet,pe,ane
231,60,90,1.015,2,2,1,1,0,0,269,...,11.500,35,9632,3.994,1,1,1,1,1,0
207,50,70,1.010,0,0,1,1,0,0,230,...,12.000,41,10400,4.600,1,1,0,1,0,0
297,53,60,1.025,0,0,1,1,0,0,116,...,15.800,45,7700,5.200,0,0,0,1,0,0
120,72,90,1.025,1,3,0,1,0,0,323,...,12.600,36,10063,3.826,0,1,1,0,0,0
310,46,60,1.020,0,0,1,1,0,0,102,...,13.200,44,11000,5.400,0,0,0,1,0,0
144,60,90,1.010,2,0,0,1,0,0,105,...,11.100,33,10500,4.100,0,0,0,1,0,0
388,51,80,1.020,0,0,1,1,0,0,94,...,15.500,46,9500,6.400,0,0,0,1,0,0
106,50,90,1.012,2,0,0,1,0,0,89,...,6.000,17,6500,3.145,1,1,0,1,1,1
58,73,80,1.020,2,0,0,0,0,0,253,...,10.500,33,7200,4.300,1,1,1,1,0,0
195,70,90,1.020,2,1,0,0,0,1,184,...,5.800,27,7786,3.456,1,1,1,0,0,0
327,30,60,1.025,0,0,1,1,0,0,120,...,13.400,44,10700,5.800,0,0,0,1,0,0
130,50,90,1.010,2,0,1,0,1,1,128,...,8.200,22,16300,2.700,0,0,0,0,1,1
193,32,90,1.025,1,0,0,0,0,0,138,...,5.500,15,2600,2.800,1,1,0,0,1,1
116,44,70,1.015,4,0,0,1,0,0,104,...,13.115,44,8713,5.435,0,0,0,1,1,0
115,47,80,1.010,0,0,1,0,0,0,160,...,12.400,44,5600,4.300,0,0,0,1,0,1
314,39,70,1.025,0,0,1,1,0,0,131,...,15.600,41,9400,4.700,0,0,0,1,0,0
290,54,70,1.020,0,0,1,1,0,0,76,...,14.800,52,8400,5.900,0,0,0,1,0,0
345,22,60,1.025,0,0,1,1,0,0,97,...,13.500,42,7900,6.400,0,0,0,1,0,0
226,64,100,1.015,4,2,0,0,0,1,163,...,7.900,26,7500,3.400,1,1,0,1,1,0
127,71,60,1.015,4,0,1,1,0,0,118,...,11.400,35,15200,4.300,1,1,0,0,1,0
389,41,80,1.025,0,0,1,1,0,0,112,...,17.000,52,7200,5.800,0,0,0,1,0,0
111,65,80,1.010,3,3,1,1,0,0,294,...,10.000,32,9000,3.900,1,1,1,1,0,0
394,50,80,1.020,0,0,1,1,0,0,137,...,14.100,45,9500,4.600,0,0,0,1,0,0
203,62,90,1.013,1,1,1,1,0,0,207,...,8.500,31,7008,3.691,1,1,0,1,0,1
22,48,80,1.025,4,0,1,0,0,0,95,...,9.800,32,6900,3.400,1,0,0,1,0,1
166,27,60,1.018,1,0,1,1,0,0,76,...,11.279,34,7701,4.432,0,0,0,0,1,1
89,50,70,1.020,0,0,1,1,0,0,109,...,14.569,41,5677,5.538,0,0,0,0,0,0
385,63,70,1.020,0,0,1,1,0,0,113,...,16.500,52,8000,5.100,0,0,0,1,0,0
372,72,60,1.020,0,0,1,1,0,0,109,...,15.000,52,10500,5.500,0,0,0,1,0,0
336,25,60,1.020,0,0,1,1,0,0,119,...,15.200,40,9200,5.200,0,0,0,1,0,0
305,41,80,1.020,0,0,1,1,0,0,122,...,17.100,41,9100,5.200,0,0,0,1,0,0
368,30,80,1.025,0,0,1,1,0,0,82,...,14.900,45,9400,5.900,0,0,0,1,0,0
95,62,90,1.015,1,0,1,1,0,0,94,...,8.105,24,7357,4.354,1,0,0,1,1,1
66,67,70,1.020,2,0,0,1,0,0,150,...,12.168,37,7351,4.228,1,1,0,1,1,0
356,34,70,1.025,0,0,1,1,0,0,87,...,17.100,47,7400,6.100,0,0,0,1,0,0
240,65,70,1.015,1,0,0,1,0,0,203,...,11.400,36,5000,4.100,1,1,0,0,1,0
328,28,70,1.020,0,0,1,1,0,0,131,...,14.287,45,8600,6.500,0,0,0,1,0,0
354,32,60,1.025,0,0,1,1,0,0,102,...,14.600,41,6800,5.100,0,0,0,1,0,0
9,53,90,1.020,2,0,0,0,1,0,70,...,9.500,29,12100,3.700,1,1,0,0,0,1
261,49,80,1.020,0,0,1,1,0,0,122,...,17.000,41,5600,4.900,0,0,0,1,0,0
350,65,70,1.025,0,0,1,1,0,0,85,...,16.100,43,9600,4.500,0,0,0,1,0,0
376,58,70,1.025,0,0,1,1,0,0,88,...,16.400,53,9100,5.200,0,0,0,1,0,0
232,50,90,1.015,1,0,0,0,0,0,144,...,11.191,36,7512,4.313,0,0,0,1,1,0
196,49,100,1.010,3,0,0,0,0,0,129,...,8.100,24,9600,3.500,1,1,0,0,1,1
5,60,90,1.015,3,0,0,1,0,0,74,...,12.200,39,7800,4.400,1,1,0,1,1,0
40,46,90,1.010,2,0,1,0,0,0,99,...,11.100,32,9100,4.100,1,0,0,1,0,0
233,51,100,1.015,2,0,1,1,0,1,93,...,13.731,45,7797,5.577,0,0,0,0,0,0
177,65,80,1.015,2,1,1,1,1,0,215,...,13.200,41,10112,4.680,0,1,0,1,0,0
109,54,70,1.015,0,1,1,1,0,0,233,...,11.700,37,7382,4.860,0,1,0,1,0,0
37,72,80,1.014,0,1,1,1,0,0,137,...,9.700,28,6900,2.500,1,1,0,0,0,1

In [67]:
df_imputed.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,hemo,pcv,wbcc,rbcc,htn,dm,cad,appet,pe,ane
0,48,80,1.020,1,0,1,1,0,0,121,...,15.4,44,7800,5.200,1,1,0,1,0,0
1,7,50,1.020,4,0,1,1,0,0,96,...,11.3,38,6000,5.334,0,0,0,1,0,0
2,62,80,1.010,2,3,1,1,0,0,423,...,9.6,31,7500,3.829,0,1,0,0,0,1
3,48,70,1.005,4,0,1,0,1,0,117,...,11.2,32,6700,3.900,1,0,0,0,1,1
4,51,80,1.010,2,0,1,1,0,0,106,...,11.6,35,7300,4.600,0,0,0,1,0,0

In [68]:
cleaned_df = pd.concat([df_imputed, target_col], axis=1)

In [69]:
cleaned_df.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wbcc,rbcc,htn,dm,cad,appet,pe,ane,class
0,48,80,1.020,1,0,1,1,0,0,121,...,44,7800,5.200,1,1,0,1,0,0,1
1,7,50,1.020,4,0,1,1,0,0,96,...,38,6000,5.334,0,0,0,1,0,0,1
2,62,80,1.010,2,3,1,1,0,0,423,...,31,7500,3.829,0,1,0,0,0,1,1
3,48,70,1.005,4,0,1,0,1,0,117,...,32,6700,3.900,1,0,0,0,1,1,1
4,51,80,1.010,2,0,1,1,0,0,106,...,35,7300,4.600,0,0,0,1,0,0,1

In [70]:
cleaned_df.isnull().sum()

age      0
bp       0
sg       0
al       0
su       0
rbc      0
pc       0
pcc      0
ba       0
bgr      0
bu       0
sc       0
sod      0
pot      0
hemo     0
pcv      0
wbcc     0
rbcc     0
htn      0
dm       0
cad      0
appet    0
pe       0
ane      0
class    0
dtype: int64

In [71]:
cleaned_df.to_csv("/content/drive/MyDrive/Colab Notebooks/CKD Project/cleaned_data_ckd.csv", index=False)

In [72]:
joblib.dump({"knn_imputer": knn_imputer,
             "imputer_scaler": scaler}, '/content/drive/MyDrive/Colab Notebooks/CKD Project/imputer_scaler.pkl')

['/content/drive/MyDrive/Colab Notebooks/CKD Project/imputer_scaler.pkl']